config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#home"

  get "/help",   to: "static_pages#help"
  get "/about",  to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 8 }, allow_blank: true

  # Возврашает дайджест для указаной строки
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
          BCrypt::Engine::MIN_COST :
          BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #Возврашает случайный токен
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Запомнить пользователя в базе данных для использования в постоянных сеансах
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end

  #Возвращает true, если указаный токен соотвествует дайджесту
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(self.remember_digest).is_password?(remember_token)
  end

  #Забыть пользователя
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      forwarding_url = session[:forwarding_url]
      reset_session
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      log_in user
      redirect_to forwarding_url || user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end
  

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      # Автоматический вход после регистрации
      log_in(@user)
      flash[:success] = "Welcome to Sample App!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Users deleted!"
    redirect_to users_path
  end

  private
    
    def user_params
      params.require(:user).permit(:name, :email, 
                :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in"
        redirect_to login_path
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url, status: :see_other) unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  

  def full_title(page_title='')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end 
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #осуществляет вход данного пользователя
  def log_in(user)
    session[:user_id] = user.id
  end

  #осуществляет выход текущего пользователя
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #возврашает текушего вошедшего пользователя (если есть)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in(user)
        @current_user = user
      end
    end
  end 
  

  #возврашает true, если полльзователь зарегестрирован, иначе 
  #возврашает false
  def logged_in?
    !current_user.nil?
  end

  #Запоминает пользователя в постоянном сеансе
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #Закрывает постоянный сеанс
  def forget(user)
    user.forget 
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  #Возврашает true, если данный пользователь является текущим
  def current_user?(user)
    user == current_user
  end

  # Перенаправить по схраненному адрессу или на страницу по умолчанию
  # def redirect_back_or(default)
  #   redirect_to(session[:forwarding_url] || default)
  #   session.delete(:forwarding_url)
  # end

  # Запомнить Url
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar img-fluid rounded-start")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
 
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
   <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
  </small>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <li class="nav-item"><%= link_to "About", about_path, class: "nav-link active fs-5 font-monospace" %></li>
      <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link active fs-5 font-monospace" %></li>
      <li class="nav-item"><a href="https://rubyonrails.org/blog/" class="nav-link active fs-5 font-monospace">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg border rounded-3" style="background-color: #2F4F4F;">
  <div class="container-fluid">
    <%= link_to 'SAMPLE APP', root_path, class: "navbar-brand text-white fw-bold fs-4" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link active text-white fs-5" %></li>
      <li class="nav-item"><%= link_to "Help", help_path, class: "nav-link active text-white fs-5" %></li>
      
    <% if logged_in? %>  
      <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link active text-white fs-5" %></li>
        <div class="dropdown me-1">
          <button type="button" class="nav-link active text-white fs-5 dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" data-bs-offset="10,20">
            Account
          </button>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
            <li class="divider"></li>
            <li><%= button_to "Log out", logout_path, method: :delete, class: "dropdown-item" %> </li>
          </ul>
        </div>

    <% else %>
      <li><%= link_to "Log in", login_path(current_user), class: "nav-link active text-white fs-5" %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script src="https://kit.fontawesome.com/ecb049080c.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
        <%= render 'layouts/header' %>

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %> mt-3">
            <%= message %>
          </div>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
      
        <% if Rails.env.development? %>
          <div class="alert alert-warning mt-1" role="alert">
              <p class="fs-5 font-monospace fw-semibold mb-1"><%= debug(params) %></p> 
          </div>
        <% end %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="container">
    <div class="alert alert-danger" role="alert">
        The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
  The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a>, part of the
  <a href="https://www.learnenough.com/">Learn Enough</a> family of
  tutorials, is a
  <a href="https://www.railstutorial.org/book">book</a> and
  <a href="https://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="https://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample app for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
  To get help on this sample app, see the
  <a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="container py-4">

   <div class="p-5 mb-4 bg-body-tertiary border rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to the Sample App</h1>
        <p class="col-md-8 fs-4">This is the home page for the
        <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
          sample application.</p>
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      </div>
    </div>
  </div>

  <%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
                        "https://rubyonrails.org/" %>

app/views/users/_form.html.erb
           <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                <%= render "shared/error_messages" %>
                <%= form_with model: @user, class: "mx-1 mx-md-4" do |f|%>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.text_field :name, class: "form-control", placeholder: "Your Name"  %>
                    </div>
                  </div>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                       <%= f.email_field :email, class: "form-control", placeholder: "Your Email"  %>
                    </div>
                  </div>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
                    </div>
                  </div>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat your password" %>
                    </div>
                  </div>
                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= f.submit 'Create my account', class: "btn btn-primary btn-lg" %>
                  </div>
                <% end %>
              </div>
            </div>
          

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Update your profile</p>
 
<%= render 'form' %>

  <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a> 
  </div>

 

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">All Users</p>


<%= will_paginate %>
<ul class="list-group list-group-light">
<% @users.each do |user| %>
  <li class="list-group-item">
      <%= gravatar_for(user)%>
      <b><%= link_to user.name, user %></b>
      <% if current_user.admin? && !current_user?(user) %>
          <%= link_to "delete", user, data: { turbo_method: :delete } %>
      <% end %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign Up</p>
<%= render "form" %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for(@user) %>
          <%= @user.name %>
        </h1>
      </section>
    </aside>
  </div>

  